name: lint

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0
      - uses: cachix/install-nix-action@v17
      - name: Install
        run: nix develop --command pnpm install 
      - name: Lint 
        run: nix develop --command pnpm lint
