name: lint

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
      - uses: cachix/install-nix-action@v17
      - name: Install
        run: nix develop --command pnpm install 
      - name: Lint 
        run: nix develop --command pnpm lint
